import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { lang } from "next/root-params";
import { notFound } from "next/navigation";
import { hasLocale, locales } from "@/lib/i18n-config";
import { siteUrl } from "@/lib/site-config";
import { Providers } from "@/components/global/providers";
import { SiteHeader } from "@/components/shared/site-header";
import { SiteFooter } from "@/components/shared/site-footer";
import { getDictionary } from "./dictionaries";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // Resolves the relative canonical/alternate/social URLs declared per route.
  metadataBase: new URL(siteUrl),
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({ children }: LayoutProps<"/[lang]">) {
  const rawLocale = await lang();
  if (!hasLocale(rawLocale)) notFound();
  const locale = rawLocale;
  const dict = await getDictionary();

  return (
    <html
      lang={locale}
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <SiteHeader
            lang={locale}
            nav={dict.nav}
            themeLabels={dict.theme}
            langLabels={dict.language}
          />
          <main className="flex-1">{children}</main>
          <SiteFooter lang={locale} nav={dict.nav} footer={dict.footer} />
        </Providers>
      </body>
    </html>
  );
}
